language: generic 
sudo: required
services:
    - docker
before_install:
    - docker build -f Dockerfile.dev -t akshazsingh/trial .


script:
    - docker run -e CI=true akshazsingh/trial npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "Trial"
    env: "Trial-env"
    bucket: "elasticbeanstalk-us-east-2-149958623134"
    bucket_path: "Trial"
    on:
        branch: "master"
    access_key_id: $access_key_id
    secret_access_key: "$secret_access_key"