language: generic 
sudo: required
services:
    - docker
before_install:
    - docker build -f Dockerfile.dev -t akshazsingh/trial .


script:
    - docker run -e CI=true akshazsingh/trial npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker-trial"
    env: "DockerTrial-env"
    bucket: "elasticbeanstalk-us-east-2-149958623134"
    bucket_path: "docker-trial"
    on:
        branch: "master"
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY