language: generic 
sudo: required
services:
    - docker
before_install:
    - docker build -f Dockerfile.dev -t akshazsingh/trial .


script:
    - docker run -e CI=true akshazsingh/trial npm run test -- --coverage